// Mocks generated by Mockito 5.4.4 from annotations
// in iot_app/test/features/iot/domain/usecases/get_devices_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:iot_app/core/errors/failures.dart' as _i5;
import 'package:iot_app/features/iot/domain/entities/iot_device.dart' as _i6;
import 'package:iot_app/features/iot/domain/entities/sensor_data.dart' as _i7;
import 'package:iot_app/features/iot/domain/repositories/iot_device_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IotDeviceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIotDeviceRepository extends _i1.Mock
    implements _i3.IotDeviceRepository {
  MockIotDeviceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.IotDevice>>> getDevices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDevices,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.IotDevice>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.IotDevice>>(
          this,
          Invocation.method(
            #getDevices,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.IotDevice>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>> getDeviceById(
          String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeviceById,
          [deviceId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>.value(
            _FakeEither_0<_i5.Failure, _i6.IotDevice>(
          this,
          Invocation.method(
            #getDeviceById,
            [deviceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>> addDevice(
          _i6.IotDevice? device) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDevice,
          [device],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>.value(
            _FakeEither_0<_i5.Failure, _i6.IotDevice>(
          this,
          Invocation.method(
            #addDevice,
            [device],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>> updateDevice(
          _i6.IotDevice? device) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDevice,
          [device],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>.value(
            _FakeEither_0<_i5.Failure, _i6.IotDevice>(
          this,
          Invocation.method(
            #updateDevice,
            [device],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> removeDevice(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeDevice,
          [deviceId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #removeDevice,
            [deviceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>> connectToDevice(
          String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToDevice,
          [deviceId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>.value(
            _FakeEither_0<_i5.Failure, _i6.IotDevice>(
          this,
          Invocation.method(
            #connectToDevice,
            [deviceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>> disconnectFromDevice(
          String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #disconnectFromDevice,
          [deviceId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>.value(
            _FakeEither_0<_i5.Failure, _i6.IotDevice>(
          this,
          Invocation.method(
            #disconnectFromDevice,
            [deviceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.IotDevice>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> sendCommand(
    String? deviceId,
    String? command,
    Map<String, dynamic>? parameters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCommand,
          [
            deviceId,
            command,
            parameters,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #sendCommand,
            [
              deviceId,
              command,
              parameters,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.SensorData>>> getSensorData(
    String? deviceId, {
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSensorData,
          [deviceId],
          {
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.SensorData>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.SensorData>>(
          this,
          Invocation.method(
            #getSensorData,
            [deviceId],
            {
              #startDate: startDate,
              #endDate: endDate,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.SensorData>>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, _i7.SensorData>> streamSensorData(
          String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamSensorData,
          [deviceId],
        ),
        returnValue: _i4.Stream<_i2.Either<_i5.Failure, _i7.SensorData>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.Failure, _i7.SensorData>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.IotDevice>>> scanForDevices() =>
      (super.noSuchMethod(
        Invocation.method(
          #scanForDevices,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.IotDevice>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.IotDevice>>(
          this,
          Invocation.method(
            #scanForDevices,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.IotDevice>>>);
}
