targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
      riverpod_generator:
        enabled: true
        options:
          provider_name_prefix: ""
          provider_family_name_prefix: ""
      freezed:
        enabled: true
